from importlib import import_module

from sqlalchemy import BigInteger, Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable


def test_appointment_status_code_model_matches_database_schema():
    model = import_module(
        "src.models.appointment_status_code"
    ).AppointmentStatusCode
    table = model.__table__

    assert table.name == "appointment_status_codes"
    assert set(table.c.keys()) == {"id", "created_at", "value"}
    assert isinstance(table.c.id.type, BigInteger)
    assert table.c.id.primary_key
    assert not table.c.id.nullable
    assert table.c.id.identity is not None
    assert table.c.id.identity.always is False
    assert table.c.created_at.type.timezone
    assert not table.c.created_at.nullable
    assert str(table.c.created_at.server_default.arg) == "now()"
    assert isinstance(table.c.value.type, Text)
    assert table.c.value.nullable

    ddl = str(CreateTable(table).compile(dialect=postgresql.dialect()))
    assert "GENERATED BY DEFAULT AS IDENTITY" in ddl
